require('express-async-errors')
const Post = require('../models/Post')

// _id is generated by "mongoose"
exports.getPosts = async(req,res)=>{
    // if you dont populate "post will look lke"
    // const Post ={
    //     category : Object Object, => like that basicely, you wont be able to read data
    //     title:"hey",
    //     content:'my content',
    //     published:tru

    // }
    
    // so when u use category "first parameter" will be the name of the 
    // key word in this exam , in post module "category"
    // the second parameter is the "name " which we have in category module
    // we can have more than one paramater in "category" model
    //so if you only give the name property then you will only fecth
   // the name property  entier property or object
   // it is like a "JOIN" u just want to get some property not all
    const data = await Post.find().populate([{path:'category',select:'name'},{path:'user',select:'name'}])
    res.status(200).json({
        succes:true,
        data:data,
        count :data.length
    })
}

exports.postPosts = async(req,res)=>{
    // this line is gonna show the user "id" in each pot
    // so we are getting it from "seession.storage",
    // because when we create auser , we save it's id in session storage
    // req.body.user: This is assigning the value of 
    //req.session.user._id to req.body.user.
    // It implies that the user ID is being attached to 
    //the request body, possibly for further processing or
    // storage in a database.
    req.body.user = req.session.user._id
    const data = await Post.create(req.body)
    res.status(201).json({
        succes:true,
        data:data
    })

}

exports.getPost = async(req,res)=>{

    // we should populete again 
    // beacuse it is readind data and we have an "foreing" key
    const data = await Post.find({_id:req.params.id}).populate('category','name')
    res.status(200).json({
        succes: true,
        data :data
    })
}

exports.putPost = async(req,res)=>{

    const post = await Post.findById(req.params.id)
    // we need to convert into a String because it "req.session.user_id" is an Object
    if(post.user.toString() !== req.session?.user?._id.toString())
    throw new ErrorResponse(403, "No Permission: Not owner")
    // it is not passive data like "getting"
    // it is an active to update the data that's why we dont 
    // need to do populate in here
    const data = await Post.findByIdAndUpdate(req.params.id, req.body,{new:true, runvalidators:true})
    res.status(200).json({
        succes:true,
        data:data
    })
}

exports.deletePost = async (req,res)=>{
    const data = await Post.findByIdAndDelete(req.params.id)
    res.status(204).json({
        succes:true,
        data:{}
    })
}

// GET  /categories/:catId/posts
// This function is likely part of a scenario where
//  you want to get all posts within a certain category,
//   and it uses the populate method to include details of
//    the category associated with each post in the result.
exports.getCategoryPosts = async(req,res)=>{
    const data = await Post.find({category: req.params.catId}).populate('category','name')
    res.status(200).json({
        success: true,
        data:date,
        count: data.length
    })
}